/// Failing runs per scenario and noise model at the Task 7 baseline (fix
/// round 1, tracker at 6800fd4), under the suite's metrics and run counts
/// (gate models 200 runs, Gaussian σ8 100). The stress model is ratcheted
/// against it (baseline + 3); Task 8 reports its changes as "baseline → now"
/// per pair. Regenerate from a FOLLOW_SCENARIOS_ALL + _PRINT run only when a
/// change deliberately moves the baseline.
const followScenariosBaseline = <String, Map<String, int>>{
  'L-shape · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 7,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · reverse from the finish · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 4,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 1,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 1,
  },
  'L-shape · mid-route backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 3,
    'gaussian σ8': 11,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route forward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 1,
    'gaussian σ8': 8,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 16,
    'gaussian σ8': 28,
    'correlated walk σ3 ρ0.9': 1,
  },
  'L-shape · mid-route forward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route backward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 14,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 10s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 43,
    'gaussian σ8': 50,
    'correlated walk σ3 ρ0.9': 6,
  },
  'L-shape · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 7,
    'gaussian σ8': 32,
    'correlated walk σ3 ρ0.9': 2,
  },
  'L-shape · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 64,
    'gaussian σ8': 56,
    'correlated walk σ3 ρ0.9': 52,
  },
  'L-shape · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 9,
    'gaussian σ8': 32,
    'correlated walk σ3 ρ0.9': 10,
  },
  'L-shape · stand 60s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 80,
    'gaussian σ8': 83,
    'correlated walk σ3 ρ0.9': 82,
  },
  'L-shape · 50 m off-route excursion · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 8,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · flip mid-ride, back to the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 11,
    'correlated walk σ3 ρ0.9': 2,
  },
  'square · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 44,
    'correlated walk σ3 ρ0.9': 4,
  },
  'square · reverse from the finish · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 6,
    'gaussian σ8': 34,
    'correlated walk σ3 ρ0.9': 11,
  },
  'square · mid-route forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 2,
    'gaussian σ8': 36,
    'correlated walk σ3 ρ0.9': 9,
  },
  'square · mid-route backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 2,
    'gaussian σ8': 38,
    'correlated walk σ3 ρ0.9': 6,
  },
  'square · across the seam forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 1,
    'gaussian σ5': 2,
    'gaussian σ8': 21,
    'correlated walk σ3 ρ0.9': 43,
  },
  'square · across the seam backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 4,
    'gaussian σ8': 33,
    'correlated walk σ3 ρ0.9': 8,
  },
  'square · mid-route forward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 1,
    'gaussian σ8': 87,
    'correlated walk σ3 ρ0.9': 13,
  },
  'square · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 23,
    'gaussian σ8': 90,
    'correlated walk σ3 ρ0.9': 17,
  },
  'square · mid-route forward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 10,
    'correlated walk σ3 ρ0.9': 7,
  },
  'square · mid-route backward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 2,
    'gaussian σ8': 20,
    'correlated walk σ3 ρ0.9': 4,
  },
  'square · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 6,
    'gaussian σ8': 57,
    'correlated walk σ3 ρ0.9': 5,
  },
  'square · stand 10s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 47,
    'gaussian σ8': 75,
    'correlated walk σ3 ρ0.9': 15,
  },
  'square · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 10,
    'gaussian σ8': 82,
    'correlated walk σ3 ρ0.9': 16,
  },
  'square · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 72,
    'gaussian σ8': 99,
    'correlated walk σ3 ρ0.9': 59,
  },
  'square · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 23,
    'gaussian σ8': 96,
    'correlated walk σ3 ρ0.9': 38,
  },
  'square · stand 60s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 1,
    'gaussian σ5': 83,
    'gaussian σ8': 98,
    'correlated walk σ3 ρ0.9': 106,
  },
  'square · flip mid-ride, one lap back · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 2,
    'gaussian σ8': 56,
    'correlated walk σ3 ρ0.9': 9,
  },
  '2 km loop · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 13,
    'correlated walk σ3 ρ0.9': 3,
  },
  '2 km loop · reverse from the finish · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 3,
    'gaussian σ8': 24,
    'correlated walk σ3 ρ0.9': 16,
  },
  '2 km loop · across the seam forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 3,
    'gaussian σ8': 15,
    'correlated walk σ3 ρ0.9': 34,
  },
  '2 km loop · across the seam backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 3,
    'gaussian σ8': 17,
    'correlated walk σ3 ρ0.9': 3,
  },
  '2 km loop · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 30,
    'gaussian σ8': 31,
    'correlated walk σ3 ρ0.9': 7,
  },
  '2 km loop · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 69,
    'gaussian σ8': 71,
    'correlated walk σ3 ρ0.9': 46,
  },
  '2 km loop · 50 m off-route excursion · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 7,
    'correlated walk σ3 ρ0.9': 4,
  },
  'out-and-back · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 34,
    'gaussian σ5': 97,
    'gaussian σ8': 79,
    'correlated walk σ3 ρ0.9': 12,
  },
  'out-and-back · forward from 2–20 m past the start · slow': {
    'noiseless': 0,
    'uniform ±5 m': 174,
    'gaussian σ5': 195,
    'gaussian σ8': 100,
    'correlated walk σ3 ρ0.9': 105,
  },
  'out-and-back · forward from 2–20 m past the start · fast': {
    'noiseless': 0,
    'uniform ±5 m': 5,
    'gaussian σ5': 33,
    'gaussian σ8': 40,
    'correlated walk σ3 ρ0.9': 1,
  },
  'out-and-back · mid-route forward (way out) · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 67,
    'gaussian σ5': 134,
    'gaussian σ8': 90,
    'correlated walk σ3 ρ0.9': 12,
  },
  'out-and-back · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 38,
    'gaussian σ5': 113,
    'gaussian σ8': 85,
    'correlated walk σ3 ρ0.9': 43,
  },
  'out-and-back · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 56,
    'gaussian σ5': 122,
    'gaussian σ8': 92,
    'correlated walk σ3 ρ0.9': 34,
  },
  'out-and-back · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 45,
    'gaussian σ5': 134,
    'gaussian σ8': 100,
    'correlated walk σ3 ρ0.9': 52,
  },
  'lollipop · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 1,
    'gaussian σ5': 18,
    'gaussian σ8': 33,
    'correlated walk σ3 ρ0.9': 9,
  },
  'lollipop · mid-loop forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 42,
    'gaussian σ5': 91,
    'gaussian σ8': 83,
    'correlated walk σ3 ρ0.9': 18,
  },
  'lollipop · mid-loop backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 40,
    'gaussian σ5': 92,
    'gaussian σ8': 81,
    'correlated walk σ3 ρ0.9': 12,
  },
  'lollipop · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 35,
    'gaussian σ5': 90,
    'gaussian σ8': 83,
    'correlated walk σ3 ρ0.9': 12,
  },
  'lollipop · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 42,
    'gaussian σ5': 113,
    'gaussian σ8': 95,
    'correlated walk σ3 ρ0.9': 57,
  },
  'lollipop · joined at the start/finish, ridden reverse: forward by default, flipped at the top of the stem · cruise':
      {
        'noiseless': 0,
        'uniform ±5 m': 33,
        'gaussian σ5': 79,
        'gaussian σ8': 71,
        'correlated walk σ3 ρ0.9': 176,
      },
  'out-and-back 1 km · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 137,
    'gaussian σ5': 162,
    'gaussian σ8': 90,
    'correlated walk σ3 ρ0.9': 100,
  },
  'out-and-back 1 km · forward 200 m from 2–20 m past the start · slow': {
    'noiseless': 0,
    'uniform ±5 m': 4,
    'gaussian σ5': 22,
    'gaussian σ8': 33,
    'correlated walk σ3 ρ0.9': 7,
  },
  'out-and-back 1 km · mid-route forward (way out) · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 136,
    'gaussian σ5': 170,
    'gaussian σ8': 91,
    'correlated walk σ3 ρ0.9': 88,
  },
  'out-and-back 1 km · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 151,
    'gaussian σ5': 169,
    'gaussian σ8': 95,
    'correlated walk σ3 ρ0.9': 127,
  },
};
