/// Failing runs per scenario and noise model after the Task 8 tracker rework
/// (signed local direction decision), under the suite's metrics and run
/// counts (gate models 200 runs, Gaussian σ8 100). The stress model is
/// ratcheted against it (baseline + 3). Regenerate from a
/// FOLLOW_SCENARIOS_ALL + _PRINT run only when a change deliberately moves
/// the baseline.
const followScenariosBaseline = <String, Map<String, int>>{
  'L-shape · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · reverse from the finish · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route forward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route forward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · mid-route backward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 10s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · stand 60s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · 50 m off-route excursion · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'L-shape · flip mid-ride, back to the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'square · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 5,
  },
  'square · reverse from the finish · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 3,
  },
  'square · mid-route forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 3,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · mid-route backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · across the seam forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 5,
  },
  'square · across the seam backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · mid-route forward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 4,
    'correlated walk σ3 ρ0.9': 5,
  },
  'square · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 8,
    'correlated walk σ3 ρ0.9': 8,
  },
  'square · mid-route forward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 3,
    'correlated walk σ3 ρ0.9': 4,
  },
  'square · mid-route backward · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 2,
  },
  'square · stand 10s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 3,
    'correlated walk σ3 ρ0.9': 4,
  },
  'square · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 4,
    'correlated walk σ3 ρ0.9': 4,
  },
  'square · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 4,
    'correlated walk σ3 ρ0.9': 1,
  },
  'square · stand 60s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 3,
    'correlated walk σ3 ρ0.9': 3,
  },
  'square · flip mid-ride, one lap back · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 4,
  },
  '2 km loop · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 3,
  },
  '2 km loop · reverse from the finish · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 1,
  },
  '2 km loop · across the seam forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 1,
  },
  '2 km loop · across the seam backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 3,
  },
  '2 km loop · mid-route backward · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 1,
  },
  '2 km loop · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  '2 km loop · 50 m off-route excursion · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 1,
  },
  'out-and-back · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  'out-and-back · forward from 2–20 m past the start · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 31,
    'correlated walk σ3 ρ0.9': 3,
  },
  'out-and-back · forward from 2–20 m past the start · fast': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 2,
  },
  'out-and-back · mid-route forward (way out) · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 5,
  },
  'out-and-back · stand 10s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 1,
  },
  'out-and-back · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 3,
  },
  'out-and-back · stand 60s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 0,
    'correlated walk σ3 ρ0.9': 0,
  },
  'lollipop · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 1,
    'gaussian σ8': 3,
    'correlated walk σ3 ρ0.9': 3,
  },
  'lollipop · mid-loop forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 4,
  },
  'lollipop · mid-loop backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 5,
  },
  'lollipop · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 7,
    'correlated walk σ3 ρ0.9': 4,
  },
  'lollipop · stand 30s at the join, then backward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 1,
    'correlated walk σ3 ρ0.9': 8,
  },
  'lollipop · joined at the start/finish, ridden reverse: forward by default, flipped at the top of the stem · cruise':
      {
        'noiseless': 0,
        'uniform ±5 m': 0,
        'gaussian σ5': 0,
        'gaussian σ8': 7,
        'correlated walk σ3 ρ0.9': 3,
      },
  'out-and-back 1 km · forward from 2–20 m past the start · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 4,
    'correlated walk σ3 ρ0.9': 4,
  },
  'out-and-back 1 km · forward 200 m from 2–20 m past the start · slow': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 2,
    'correlated walk σ3 ρ0.9': 0,
  },
  'out-and-back 1 km · mid-route forward (way out) · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 3,
  },
  'out-and-back 1 km · stand 30s at the join, then forward · cruise': {
    'noiseless': 0,
    'uniform ±5 m': 0,
    'gaussian σ5': 0,
    'gaussian σ8': 5,
    'correlated walk σ3 ρ0.9': 5,
  },
};
